apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdx-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fdx-webapp
  template:
    metadata:
      labels:
        app: fdx-webapp
    spec:
      containers:
      - name: fdx-webapp
        image: thippeshanaik/fdx-webapp:IMAGE_TAG
        ports:
        - containerPort: 8080

